server:
  port: 9005

spring:
  application:
    name: board-article-read-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: board-article-read-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # key 를 kafka 에 전달할 때, 직렬화할 수 있어야 하므로
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer # value 를 kafka 에 전달할 때, 직렬화할 수 있어야 하므로
      enable-auto-commit: false


endpoints:
  board-article-service: # 게시글 조회 서비스에서는 TTL 끝난 게시글을 조회할 때 게시글 원본 정보가 필요하므로 REST API 호출을 위한 endpoint
    url: http://127.0.0.1:9000
  board-comment-service: # 게시글 조회 서비스에서는 TTL 끝난 댓글수 조회할 때 댓글 원본 정보가 필요하므로 REST API 호출을 위한 endpoint
    url: http://127.0.0.1:9001
  board-like-service: # 게시글 조회 서비스에서는 TTL 끝난 좋아요수 조회할 때 좋아요 원본 정보가 필요하므로 REST API 호출을 위한 endpoint
    url: http://127.0.0.1:9002
  board-view-service: # 게시글 조회 서비스에서는 TTL 끝난 조회수 조회할 때 조회수 원본 정보가 필요하므로 REST API 호출을 위한 endpoint
    url: http://127.0.0.1:9003

logging:
  level:
    cwchoiit.board.articleread: debug